export const USER_PREFERRED_CURRENCY = '@TronWallet:userPreferredCurrency'
export const USER_PREFERRED_LANGUAGE = '@TronWallet:userPreferredLanguage'
export const USER_STATUS = '@TronWallet:useStatus'
export const ALWAYS_ASK_PIN = '@TronWallet:alwaysAskPin'
export const USE_BIOMETRY = '@TronWallet:useBiometry'
export const ENCRYPTED_PIN = '@TronWallet:encryptedPin'
export const USER_FILTERED_TOKENS = '@TronWallet:userFilteredTokens'
export const TOKENS_VISIBLE = '@TronWallet:tokensVibility'
export const ADD = 'ADD'
export const EDIT = 'EDIT'
export const FEATURED_TOKENS = ['TWX', 'LoveHearts', 'CyberTron']
export const VERIFIED_TOKENS = ['IGG', 'Alivio', 'ReynaToken', 'BeatzCoin']
export const FIXED_TOKENS = ['TRX', ...FEATURED_TOKENS, ...VERIFIED_TOKENS]
